import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    // TODO:  нужно подумать над тем, какая будет здесь главная страничка. пока комменчу
    // 'index',
    // {
    //   type: 'category',
    //   label: 'Basics',
    //   items: [
    //     'tutorial-basics/create-a-page',
    //     'tutorial-basics/create-a-document',
    //     'tutorial-basics/create-a-blog-post',
    //     'tutorial-basics/markdown-features',
    //     'tutorial-basics/deploy-your-site',
    //     'tutorial-basics/congratulations',
    //   ],
    // },
    // {
    //   type: 'category',
    //   label: 'Extras',
    //   items: [
    //     'tutorial-extras/translate-your-site',
    //     'tutorial-extras/manage-docs-versions',
    //   ],
    // },
    'introduction',
    {
      type: 'category',
      label: 'Начало работы',
      items: [
        'getting_started/installation',
        'getting_started/howto',
      ]
    },
    {
      type: 'category',
      label: 'О Schemistry',
      items: [
        'about_schemistry/how_to_start',
        'about_schemistry/anatomy',
      ],
    },
    {
      type: 'category',
      label: 'Инструменты',
      items: [
        'integration/index',
        {
          type: 'category',
          label: 'Инструмент командной строки (CLI)',
          items: [
            'integration/cli/index',
            {
              type: 'category',
              label: 'Доступные команды',
              items: [
                'integration/cli/commands/mod/init',
                'integration/cli/commands/mod/get',
                'integration/cli/commands/mod/pull',
                'integration/cli/commands/mod/push',
                'integration/cli/commands/mod/codegen',
                'integration/cli/commands/mod/lint',
                'integration/cli/commands/mod/major',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'CI',
          items: [
            'integration/ci/index',
            {
              type: 'category',
              label: 'Supported CI systems',
              items: [
                'integration/ci/supported/github_actions/index',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Ручное разворачивание реестра',
          items: [
            'self_hosted/index',
          ],
        },
      ]
    },
  ],
};

export default sidebars;
